var apology = [
  'Forgive me...',
  'SO sorry',
  'My bad,',
  'Ah jeez-',
  'Hey... listen,',
  'Oh no!',
  'Sorry!',
  'Apologies,',
  'Oof...',
  'Yeah, about that,',
  'Hey buddy,',
  'Dang!',
  'Sorry to flake,',
  'Guess what?',
  'Sorry, champ.',
  'Youll never believe it!',
  'Hey,',
  'Rats!',
  'You know what?'

];

var subject = [
  'my dog ',
  'my cat ',
  'my mom ',
  'my daddy ',
  'my goldfish ',
  'my ex-husband ',
  'my wife ',
  'my baby ',
  'my nanny  ',
  'my ex ',
  'my brother ',
  'my professor ',
  'my grandma ',
  'my grandpa ',
  'Guy Fieri ',
  'Hillary Clinton ',
  'Obama  ',
  'Ted Cruz ',
  'George Lopez ',
  'Erich Doubek ',
  'Donald Trump ',
  'Tom Cruise ',
  'my ass ',
  'my former lover ',
  'Jeff Goldblum ',
  'the Hulk  ',
  'your mom  ',
  'the voices in my head ',
  'a ghost ',
  'Clifford the Big Red Dog ',
  'Elmo ',
  'Mega Man ',
  'Sonic the hedgehog ',
  'one of the Jonas Brothers ',
  'a guy in a mascot costume ',
  'my estranged uncle ',
  'some weeb ',
  'some guy I went to middle school with ',
  'my therapist ',
  'Gordon Ramsey ',
  'John Mulaney ',
  'my inner demons ',
  'my roommate ',
  'the Pope ',
  'Ariana Grande ',
  'my priest ',
  'my 1st grade boyfriend ',
  'Kanye West ',
  'Snoop Dog ',
  'Celine Dion ',
  'my horrible friend, Ricky ',
  'your wife ',
  'Mike Pence ',
  'Hillary Duff ',
  'Shakira',
  'my crazy neighbor ',
  'the Fedex delivery guy ',
  'my pet turtle ',
  'my step brother ',
  'Taylor Swift ',
  'my own son ',
  'some old lady on the street ',
  'the lady that waxes my eyebrows ',
  'that guy I met on tinder ',
  'my crush',
  'the Devil himself ',
  'a wild deer ',
  'the ghost of Freddy Mercury ',
  'the French exchange student',
  'my stupid girlfriend',
  'my least favorite child',
  'my clone',
  'my doctor'




];

var reason = [
  ' lost their car keys in my dog’s ass.',
  ' broke both their kneecaps.',
  ' has depression.',
  ' has the runs.',
  ' broke my Wii.',
  ' forgot to take their birth control!',
  ' just left me at the alter!',
  ' just ate my last cheese stick!',
  ' slept with my wife!',
  ' broke my heart.',
  ' is blocking out the sun.',
  ' burned the casserole.',
  ' told me I am ugly.',
  ' just started a new religion.',
  ' spoiled Harry Potter for me!',
  ' just called me a loser.',
  ' broke my heart.',
  ' is crying on my kitchen floor.',
  ' smashed the papier-mâché bowl I made for no reason.',
  ' is being a major bitch to me.',
  ' never loved and never will.',
  ' is being condescending.',
  ' wont reply to my text.',
  ' needs me to bail them out of jail.',
  ' just got a botched nose job.',
  ' wont shut up about cryptocurrency.',
  ' told me I would have bad luck today.',
  ' gave me pink eye.',
  ' grounded me.',
  ' wont leave my birthday party.',
  ' proposed!',
  ' hurt my feelings.',
  ' threw my car keys in the trash.',
  ' slashed my tires',
  ' shaved off my eyebrows in my sleep.',
  ' is handcuffed to me.',
  ' told me I cant go.',
  ' gave me a goldfish and I dont know if I can handle the responsibility.',
  ' said something racially insensitive again.',
  ' told me I am the father of their child.',
  ' peer pressured me into trying drugs.',
  ' stole my boyfriend.',
  ' threw up in my bed.',
  ' leaked my nudes.',
  ' is getting baptised.',
  ' is blocking the exits to my house',
  ' cheated on me again.',
  ' sneezed in my face.',
  ' kept me up all night talking about Israel/ Palestine',
  ' told everyone I am "problematic."',
  ' hurt my feelings.',
  ' called me fat.',
  ' threw my TV out the window because I forgot our anniversary.',
  ' ate all the food in my fridge.',
  ' showed up at my door in the rain to confess their love.',
  ' is passed out drunk and naked on my lawn.',
  ' broke into my room and drank all of my perfume.',
  ' took a shit on my laptop and closed it.',
  ' reported me to the police for pirating the Shrek movies on the internet.',
  ' told me I am bad at Fortnite.',
  ' just started a Minecraft server.',
  ' invited me to their circumcision',
  ' flicked me in the face.',
  ' just had a threesome with my parents!',
  ' stole my mattress and is currently running down the street with it.',
  ' just heard my voice crack.',
  ' published my diary in the school newspaper.',
  ' clogged my toilet and then lied about it.',
  ' farted all over my clean clothes.',
  ' is covered in vaseline, sliding around my room.',
  ' let 25 crickets loose in my bedroom.',
  ' wants my opinion on their screenplay.',
  ' used up my whole data plan having a twitter fight.',
  ' just stole my idea for a youtube channel.',
  ' took all my good underwear and sold it on craigslist',
  ' and I are playing Rock Band and almost finished Eye of the Tiger on expert level.',
  ' and I are trying to see who can hold their breath the longest.',
  ' and I are  really invested in this episode of Project Runway.',
  ' and I are fighting over whether or not a hot dog is a sandwich.',
  ' and I decided we want to  see other people.',
  ' is having boy troubles again.',
  ''

];

var excuseGen = {
  "apology": apology,
  "subject": subject,
  "reason": reason
}

function random(maxNum) {
  return Math.floor(Math.random() * (maxNum));
}

function randomString(strings) {
  var randomNumber = random(strings.length);
  return strings[randomNumber]
}

function newExcuse() {
  var apology = randomString(excuseGen["apology"])
  document.getElementById('apologyDisplay').innerHTML = apology;

  var subject = randomString(excuseGen["subject"])
  document.getElementById('subjectDisplay').innerHTML = subject;

  var reason = randomString(excuseGen["reason"])
  document.getElementById('reasonDisplay').innerHTML = reason;
}
